### ISSUE TITLE
Egg Bot randomly disconnects

### ISSUE THREAD

**Issue by Dungaboo** [mwoerner77/SVEggBot#1]
Over the course of the 30 minutes the sandwhich was active, I've had to stay glued to my computer because without reason (Finding a shiny) the egg bot will randomly disconnect and I'll have to use the start picnic option again to continue.

**Comment by Dungaboo** [comment]
Now it's decided to make ham and butter sandwhiches despite the down + right settings staying the same

**Comment by mwoerner77** [comment]
To me this sounds like sysbot is having trouble establishing a stable connection. Are you experiencing similar problems with other sysbot applications?

**Comment by Dungaboo** [comment]
Not to my knowledge. I tend to avoid running multiple sysbot programs at once, but I have never had a connection issue with LiveHex, Raidcrawler, or Sysbots Trade bot

**Comment by Dungaboo** [comment]
I seem to have found a manual workaround. I had to manually move my player in front of the basket. Otherwise I would just wander off or randomly disconnect. Now that I've been doing that, it seems the bot wants to stay online.

**Comment by Dungaboo** [comment]
It also doesn't seem to want to make new sandwhiches after the 30 minutes runs out. I'm not sure if that's an issue on my side or just something the bot doesn't do.

**Comment by mwoerner77** [comment]
That is super odd. I'll try to reproduce it, but don't know if I'll be able to.

**Comment by mwoerner77** [comment]
Could you let me know what your setup is so I can try to reproduce? What game you're playing, what switch you have, if it's docked or not, what the actual connection error says, if there are any other controllers connected besides the docked joycons, etc.

**Comment by Dungaboo** [comment]
Playing: Pokemon Scarlet
Switch: OG Switch with Atmosphere and homebrew, new Sysbotbase install (fresh install within the last month)
Not Docked, no additional controllers added.

Bit of a newb, but I don't have an error log, the program itself runs for a few minutes and then I'll notice my character idling. When that happens, on the main program on my computer, it shows that the picnic was stopped despite not finding a shiny.

As a general walkthrough of what happens: When connect and start picnic is selected the bot accurately opens the menu, starts a picnic, walks a few steps to get near the table, and selects the sandwhich. The issues start when trying to mak the sandwhich, the bananas are picked up but then dropped past the bread. Once the sandwhich is made the bot, I assume, is supposed to walk over to the basket to check eggs. This part doesn't work on my end, my character ends up just walking straight off to the side, but if I manually move myself in front of the basket it begins working.

The first few eggs seem to always be sent to the academy, but then it will start collecting some. I just have to watch the program on my computer to manually hit the start picnic button when it randomly disconnects. So far I've yet to see it make another sandwich after the 30 minute mark.

**Comment by mwoerner77** [comment]
Sounds like I need to make some of the delays configurable by the user so it can be tweaked for different connections. Also just confirming, but is this the latest version of scarlet/violet? That's what it's built for.

Also none of the eggs should be sent to the academy. I mash b through that dialog so the eggs actually land in your box

**Comment by Dungaboo** [comment]
Should be the newest version, I'll verify that shortly.

Next time I run it, I'll see if I can take a screenshot, something happens on my end that definitely sends a handful of eggs to the academy. I know says this egg will be sent to the academy and normally it cancels and I get the egg, but a few of them actually have the "Egg was sent to the academy!" pop up.

Appreciate you taking the time to troubleshoot with me.

**Comment by Dungaboo** [comment]
As an update: there doesn't seem to be any more disconnecting issues nor have I seen any eggs sent to the academy.

I ran the bot for about 30 minutes and it worked perfectly, made the level 2 sandwich, walked to the basket, and fetched eggs. Still can not get it to make another sandwich, so I stopped the picnic, cleared my boxes of non-shiny eggs, and reconnected. Now it seems to be having trouble in just walking up to the table to make the sandwich.

**Comment by mwoerner77** [comment]
I have updated the bot. Are you able to fix the issue now that delays are configurable?

**Comment by Dungaboo** [comment]
Things seem to be working! I have to mess with the sandwich ingredient settings it looks like, because it's either not picking anything up or dropping them way past the sandwich resulting in a egg level 1 instead of egg level 2 sandwhich.

**Comment by mwoerner77** [comment]
Great, I'm going to close the issue. If you are having more problems with the bot open a new issue or ping me on discord
